backend:
  name: git-gateway
  branch: dev

media_folder: static/images
public_folder: /images

collections:
  - name: "Blog"
    label: "Artigos do blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Projects"
    label: "Projetos"
    folder: "content/projects"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
