backend:
  name: git-gateway
  branch: dev

media_folder: static/images
public_folder: /images

collections:
  - name: "Blog"
    label: "Artigos do blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Projects"
    label: "Projetos"
    folder: "content/projects"
    create: true
    fields:
      - { name: date, label: "Data de início", widget: date }
      - { name: title, label: "Titulo do projeto" }
      - { name: body, label: "Texto", widget: markdown }
      - { name: active, label: "Projeto ativo?", widget: "boolean", default: true}
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Apoio"
    label: "Apoio"
    folder: "content/apoio"
    create: true
    fields:
      - { name: name, label: "Nome do apoiador" }
      - label: "Marca do apoiador"
        name: "brand"
        widget: "image"
        media_library:
          config:
            multiple: false
