backend:
  name: git-gateway
  branch: dev

media_folder: static/images
public_folder: /images

collections:
  - name: "Blog"
    label: "Artigos do blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: date, label: "Data de postagem", widget: date }
      - { name: title, label: "Título do artigo" }
      - { name: body, label: "Conteúdo", widget: markdown }
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Projects"
    label: "Projetos"
    folder: "content/projects"
    create: true
    fields:
      - { name: date, label: "Data de início", widget: date }
      - { name: title, label: "Titulo do projeto" }
      - { name: body, label: "Texto", widget: markdown }
      - { name: active, label: "Projeto ativo?", widget: "boolean", default: true}
      - label: "Imagem de destaque"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Apoio"
    label: "Apoio"
    folder: "content/apoio"
    create: true
    fields:
      - { name: title, label: "Nome do apoiador" }
      - label: "Marca do apoiador"
        name: "brand"
        widget: "image"
        media_library:
          config:
            multiple: false
  - name: "Páginas"
    label: "Páginas"
    folder: "content/paginas"
    create: true
    fields:
      - { name: title, label: "Título da página" }
      - { name: body, label: "Conteúdo", widget: markdown }
  - name: "Informações do site"
    label: "Informações do site"
    folder: "content/sitemetadata"
    create: false
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: "Sub-título do site" }
      - { name: mission, label: "Texto de missão" }
      - { name: andress, label: "Endereço" }
      - { name: tel, label: "Telefone de contato" }
      - { name: email, label: "E-mail de contato" }
      - { name: heroTitle, label: "Titulo em destaque" }
      - { name: heroText, label: "Texto em destaque" }
